### PR TITLE
trilinos: 12.12.1 -> xsdk-0.4.0-rc1

### PR DESCRIPTION
**Pull request by tristan0x**
omega-h build with trilinos@xsdk-0.4.0-rc1. So make it the default version instead of `develop`.

### CODE REVIEW

**Comment by tristan0x** [comment]
#`Wholesale tests` error:
```
[git] curl: (22) The requested URL returned error: 503
[git] ==> Fetching https://libbsd.freedesktop.org/releases/libbsd-0.8.6.tar.xz
[git] ==> Fetching from https://libbsd.freedesktop.org/releases/libbsd-0.8.6.tar.xz failed.
[git] ==> Error: FetchError: All fetchers failed for libbsd-0.8.6-zgwz3wg5lld3vaxt6wjpc3l6tjp4ajba
[git] 
[git] /jenkins/06/workspace/hpc.spack-testing/jenkins-hpc.spack-testing-372/spack/lib/spack/spack/package.py:934, in do_fetch:
[git]         931                raise FetchError("Will not fetch %s" %
[git]         932                                 self.spec.format('$_$@'), ck_msg)
[git]         933
[git]   >>    934        self.stage.create()
[git]         935        self.stage.fetch(mirror_only)
[git]         936        self._fetch_time = time.time() - start_time
[git]         937
[git] 
[git] 
[git] ==> Error: 'NoneType' object has no attribute 'endswith'
```

retest this please Jenkins

**Review by smelchio — APPROVED** [review]
LGTM!
