### PR TITLE
Bump morphio to 2.4.1

### PR DESCRIPTION
**Pull request by ferdonline**
Among others, it brings updated highfive submodule which works with hdf5 1.12

### CODE REVIEW

**Comment by matz-e** [comment]
Retest this please

**Comment by matz-e** [comment]
```
/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/bbprelman/1236772/spack-stage-py-morphio-2.4.1-l7dnod7m6asxdzy2dtlbejy5e3anyxve/spack-src/src/mut/writers.cpp(378): error #3291: invalid narrowing conversion from "morphio::enums::CellFamily" to "unsigned int"
write_attribute(g_metadata, "cell_family", std::vector<uint32_t>{morpho.cellFamily()});
```
…

**Comment by matz-e** [comment]
Outdated.
